import { Schema, SchemaOptions, SchemaTypeOpts } from 'mongoose';
import 'reflect-metadata';
import { deepMapKeys, deepMapValues, isTypedModel, TypedModel } from '..';

export interface TypeOptions<T> extends SchemaTypeOpts<T> {
	// From lemon-js
	ref?: Constructor;
	refer?: Constructor;
	child?: boolean | SchemaOptions;
	children?: boolean | SchemaOptions;
}
export type SchemaTypeOptions<T> = TypeOptions<T> | { [key: string]: any };

export type Constructor = {
	new(...args): any
};

/************************************************
 *
 * @property definition
 *
 ************************************************/

export function property<T>(target: TypedModel, propertyKey: string): void;
export function property<T>(
	meta: SchemaTypeOptions<T>
): (target: TypedModel, propertyKey: string) => void;
export function property<T>(
	targetOrMeta: TypedModel | SchemaTypeOptions<T>,
	propertyKey?: string,
) {
	if (targetOrMeta instanceof TypedModel) {
		savePropertyMeta(targetOrMeta, propertyKey);
		return;
	}

	const meta = targetOrMeta;
	return (target: TypedModel, propKey: string) => {
		savePropertyMeta(target, propKey, meta);
	};
}

function savePropertyMeta(target: TypedModel, propertyKey: string, meta: any = {}) {
	const constructor = (target.constructor as any);
	if (!constructor._meta) {
		constructor._meta = {
			properties: {},
			schemaOptions: {}
		};
	}

	const propsMeta: object = constructor._meta.properties;

	/************************************************
	 *
	 * Sub-documents / Subdocs
	 *
	 ************************************************/

	if (meta.child || meta.children) {
		let isSingleNested = Boolean(meta.child);
		let schemaOptions = isSingleNested ? meta.child : meta.children;
		let isBoolean = typeof schemaOptions === 'boolean';
		delete meta.child;
		delete meta.children;

		let childSchema = new Schema(meta, isBoolean ? undefined : schemaOptions);
		propsMeta[propertyKey] = isSingleNested ? childSchema : [childSchema];
	}

	/************************************************
	 *
	 * Validators
	 *
	 ************************************************/

	if (meta.validate && !(meta.child || meta.children)) {
		let newValidate;

		if (Array.isArray(meta.validate)) {
			if (meta.validate.length === 2 &&
				typeof meta.validate[0] === 'function' &&
				typeof meta.validate[1] === 'string') {
				// var custom = [validator, 'Uh oh, {PATH} does not equal "something".']
				// new Schema({ name: { type: String, validate: custom } });
				newValidate = {
					validator: wrapValidator(meta.validate[0]),
					message: meta.validate[1]
				};
			} else {
				// let many = [
				// 	{ validator: validator, message: 'uh oh' },
				// 	{ validator: anotherValidator, message: 'failed' }
				// ];
				// new Schema({ name: { type: String, validate: many } });
				newValidate = meta.validate.map((x) => {
					return {
						validator: wrapValidator(x.validator),
						message: x.msg ? x.msg : x.message
					};
				});
			}
		} else if (typeof meta.validate === 'function') {
			// new Schema({ name: { type: String, validate: function validator(val) {} } });
			newValidate = wrapValidator(meta.validate);
		} else {
			// new Schema({ name: { type: String, validate: {
			// 	isAsync: true,
			// 	validator: function validator(val) {}
			// }}});
			const isAsync = meta.validate.isAsync;
			newValidate = {
				isAsync,
				validator: wrapValidator(meta.validate.validator, isAsync),
				message: meta.validate.message
			};
		}

		meta.validate = newValidate;
	}

	/************************************************
	 *
	 * Types
	 *
	 ************************************************/

	// Map all refer (as a alias) to ref
	meta = deepMapKeys(meta, (val, key) => key === 'refer' ? 'ref' : key);

	// Set type according to metadata generated by typescript
	if (!meta.type && !(meta.child || meta.children)) {
		const type = Reflect.getMetadata('design:type', target, propertyKey);

		if (meta.ref && Array.isArray(meta.ref)) {
			if (meta.ref.length !== 1) throw new Error(`Expecting one referenced type for ${ propertyKey }, but received [${ meta.refer.map(x => x.name ? x.name : x.toString()).join(',') }].`);
			if (!isTypedModel(meta.ref[0])) throw new Error(`Referenced type for ${ propertyKey } is not a subclass of 'TypedModel.'`);
			let metaType = meta.ref[0];
			meta = [{ ref: metaType, type: Schema.Types.ObjectId }];
		} else {
			if (type) {
				if (isTypedModel(type)) {
					meta.ref = type;
					meta.type = Schema.Types.ObjectId;
				} else if (isTypedModel(meta.ref)) {
					meta.type = Schema.Types.ObjectId;
				} else {
					meta.type = type;
				}
			} else {
				const name = constructor.name;
				throw new Error(
					`Type of ${ name }.${ propertyKey } isn't set. Uf you use typescript ` +
					'you need to enable emitDecoratorMetadata in tsconfig.json',
				);
			}
		}
	}

	propsMeta[propertyKey] = meta;
}

function wrapValidator(validator, isAsync = false) {
	if (isAsync) {
		return function (value, callback) {
			// Validator format:
			validator(value, this, callback);
		};
	} else {
		return function (value) {
			// Validator format:
			return validator(value, this);
		};
	}
}
